### ISSUE TITLE
Avoid cloudfront caching on pre render request

### ISSUE THREAD

**Issue by lucashfreitas** [jinty/prerender-cloudfront#10]
Hello! 

I would like to apologize if this questions have been already answered before, but I am having an issue using cloudfront + pre render.

### Question 1

When google bot/others bots do the request for website, cloudfront is caching prerender  html response and always delivering HTML content, does not matters if the request is coming from a browser or a bot.

The question is: How can I tell cloudfront to not cache content if the response is pre rendered html? I think will be something as the project described in this quote:

_"As prerender.io does NOT want any Cloudfront caching (see https://github.com/prerender/prerender/issues/93#issuecomment-366774910) we disable that by including a X-Prerender-Cachebuster header which effectively disables cloudfront caching."_

Anyone has faced same problem and found out a solution? Everything is working fine except this strange cache behaviour. 

I will keep searching and If I found a solution I will update this issue. 

Many Thanks!

**Comment by jinty** [comment]
the relevant bits are here:
```
          ForwardedValues:
            QueryString: false
            Headers:
              - "X-Prerender-Cachebuster"
```
the above, in prerender-cloudfront.yaml tells cloudfront to partition the cache on the value of the X-Prerender-Cachebuster header.

This header is set in the SetPrerenderHeader lambda function to the current timestamp. i.e. different every time. That effectively disables caching. SetPrerenderHeader operates on the request before it enters the caching layer and can modify the incoming HTTP headers.

**Comment by lucashfreitas** [comment]
Many Thanks @jinty! 

Would not make sense to do everything, including redirect in VIEWER REQUEST event instead of set headers and then do redirect in origin request? I was thinking about that because in viewer event, the incoming request has not even touched the cache layer, so the redirect would works fine with only one lambda function. What do you think? Please refer to attached image from aws documentation.

![cloudfront-events](https://user-images.githubusercontent.com/11416392/51097311-f41f6480-1827-11e9-9d07-65c79ea89c79.png)

**Comment by jinty** [comment]
My use of the word redirect in "RedirectToPrerender" is unfortunate. It
does not issue an HTTP redirect. I tells cloudfront to not use the default
backend but rather to send the request to pretender.

It may be that you can now do that at the viewer request stage and avoid
the caching layer. If possible that would be a great simplification!

**Comment by lucashfreitas** [comment]
Yes, you're right! i think what we doing most look like a backend "replacement" than a redirect! 

I am doing tests right now. If its work fine I can submit a pull request :) 

Many Thanks again!

**Comment by augustosamame** [comment]
Hi @jinty. When you say that the header "X-Prerender-Cachebuster", "effectively disables caching" do you mean it will disable caching just for calls detected as bots, and therefore will serve content from source? Or does it disable caching for all calls and therefore we're basically negating most of Cloudfront's advantages? I'm pretty sure it's the former, but just making sure.

**Comment by luiscastillocr** [comment]
We are using the AWS CDN in front of an NGINX, If I understanding this correctly if you pass `X-Prerender-Cachebuster` to pretender like this

```
proxy_set_header "X-Prerender-Cachebuster" "$msec";
```

The buster header should be passed to the origin, what is not clear for me is the CDN configuration you should have to let the header pass, we have something like this in our cache policy

![image](https://user-images.githubusercontent.com/3835089/115096395-1eb66700-9ee2-11eb-9c8f-a4b370c2ab31.png)

please notice the `X-Prerender-Cachebuster` header is whitelisted to be part of the cache key, but I am not seeing this header reaching NGINX, am I missing something?

The issue I am having is the pre-rendered cached page is being served to the regular web browsers

here is the `@prerender` configuration, any advice will be appreciated.

```
location @prerender {
        proxy_set_header "X-Prerender-Token" "TOKEN";
        proxy_set_header "X-Prerender-Cachebuster" "$msec";
       
       # debugging headers
        add_header "X-Prerender-Cachebuster" "$http_x_prerender_cachebuster" always;

        # don't let rate limiting or server errors interrupt a request
        proxy_intercept_errors on;
        error_page 429 500 502 503 504 =200 /index.html;

        set $prerender 0;
        set $prerender_protocol "https";

        if ($http_user_agent ~* "wikirealtybot|googlebot|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest\/0\.|pinterestbot|slackbot|vkShare|W3C_Validator|whatsapp|metainspector") {
            set $prerender 1;
        }
        if ($args ~ "_escaped_fragment_") {
            set $prerender 1;
        }
        if ($http_user_agent ~ "prerender") {
            set $prerender 0;
        }
        if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot|map)") {
            set $prerender 0;
        }
        if ($http_prerendered ~ true) {
            set $prerender 0;
        }

        # this serves stale while waiting on a request to service.prerender.cloud to update cache (after 1st req)
        # see http://serverfault.com/questions/576402/nginx-serving-stale-cache-response-while-updating
        proxy_cache_use_stale updating;

        # http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_key
        proxy_cache_key $prerender$scheme$proxy_host$uri$is_args$args;

        # resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
        resolver 8.8.8.8;

        if ($prerender = 1) {
            # setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
            set $prerender "service.prerender.io";
            rewrite .* /$prerender_protocol://$host$request_uri? break;
            proxy_pass http://pre-render;
        }

        if ($prerender = 0) {
            rewrite .* /index.html break;
        }
    }
```

**Comment by 719media** [comment]
@lucashfreitas 
Hello from 3 years since your last comment. I suppose if you tried to handle this all inside the ViewerRequest (as opposed to also utilizing the OriginRequest), you wouldn't be able to cache any response at the cloudfront layer.

In other words, if a "prerender client" (e.g. facebook bot) hit the (same) page 1000 times over 5 minutes, you'd be bypassing the cloudfront caching each time, as shown by your image posted above. You may or may not want this.

If you DO want prerender requests to be cached at the cloudfront layer, then you'd have to handle it inside of the OriginRequest.

Anyway, did you have any success with any implementation? Just about to do this myself.
