### ISSUE TITLE
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions

### ISSUE THREAD

**Issue by dusan91judo** [jinty/prerender-cloudfront#22]
Hello people !

Does anyone have the same problem with current setup as I have ?
I followed installation instruction, but it is not working.
Here is the image when I hit it from browser.

![Cloudfront](https://user-images.githubusercontent.com/8835766/143691885-4d4dbf89-80d3-41e9-aad2-821775fb9f95.png)

If anyone can help, I will appreciate it !

**Comment by Zer0Name** [comment]
im having the same issue!!

**Comment by Zer0Name** [comment]
@dusan91judo Did you find a solution?

**Comment by dusan91judo** [comment]
No I didn't. I think that Amazon update his services and prerender-cloudfront.yaml is not updated.

**Comment by lluczo** [comment]
I created a PR that solves this issue
https://github.com/jinty/prerender-cloudfront/pull/23

**Comment by dusan91judo** [comment]
Hope it will be merged soon
