### ISSUE TITLE
Images and css not loading for bots

### ISSUE THREAD

**Issue by jasonandres** [jinty/prerender-cloudfront#7]
I'm having an issue with images and css not loading for bots. If I'm understanding the issue correctly,   the request at the edge location sees the user agent is a bot and sends the request (by passing cloud front cache) to the prerender server, it renders the page, caches it and returns the result with the full html.  

When an image or css is with-in the HTML it's requested, the edge location sees it's a bot and sends the request to the prerender servers. But the prerender servers do not cache the assets.

All our assets are relative urls. Not sure if I just have something mis-configured or if the redirect needs to exclude redirection of assets.

**Comment by jinty** [comment]
Hi Jason,

Thanks for the feedback, you're absolutely right. I had a look at how the other middleware avoids sending image requests to prerender.io and cribbed that. It should be fixed in the current master.

Thanks for the issue
